const ZH_CN_ATTRIBUTE_NAMES = [
  "aria-label",
  "title",
  "placeholder",
  "alt",
] as const;

const EXACT_TRANSLATIONS: Record<string, string> = {
  "Home": "首页",
  "Issues": "事项",
  "Create": "新建",
  "Agents": "代理",
  "Inbox": "收件箱",
  "Dashboard": "仪表盘",
  "WORK": "工作",
  "Routines": "例程",
  "Goals": "目标",
  "PROJECTS": "项目",
  "Org": "组织",
  "Costs": "成本",
  "Settings": "设置",
  "Instance Settings": "实例设置",
  "Instance settings": "实例设置",
  "Company Settings": "公司设置",
  "Company settings": "公司设置",
  "Company": "公司",
  "access": "访问权限",
  "company access": "公司访问权限",
  "Access": "访问权限",
  "Invites": "邀请",
  "Heartbeats": "心跳",
  "Plugins": "插件",
  "Plugins are alpha.": "插件功能仍处于 alpha 阶段。",
  "Plugin Settings": "插件设置",
  "Configuration": "配置",
  "Automation": "自动化",
  "Permissions & Configuration": "权限与配置",
  "Environments": "环境",
  "Adapters": "适配器",
  "Profile": "个人资料",
  "Edit profile": "编辑个人资料",
  "View profile": "查看个人资料",
  "Documentation": "文档",
  "Sign out": "退出登录",
  "Signing out...": "正在退出登录...",
  "Sign in": "登录",
  "Sign in to continue": "登录后继续",
  "Sign in and continue": "登录并继续",
  "Create account": "创建账户",
  "Create account and continue": "创建账户并继续",
  "Create your account": "创建你的账户",
  "Create your Paperclip account": "创建 Paperclip 账户",
  "Sign in to Paperclip": "登录 Paperclip",
  "Create your first company": "创建第一个公司",
  "Create another company": "创建另一个公司",
  "Create invite": "创建邀请",
  "Invite created": "邀请已创建",
  "New Company": "新建公司",
  "New issue": "新建事项",
  "New Issue": "新建事项",
  "Search": "搜索",
  "Search for a command to run...": "搜索要运行的命令...",
  "Search by name or email": "按姓名或邮箱搜索",
  "Keyboard shortcuts": "键盘快捷键",
  "Open account menu": "打开账户菜单",
  "Skip to Main Content": "跳到主内容",
  "Skip to Main content": "跳到主内容",
  "Skip to Main 内容": "跳到主内容",
  "Open Paperclip docs in a new tab.": "在新标签页打开 Paperclip 文档。",
  "Jump back to the last settings page you opened.": "返回上次打开的设置页。",
  "Update your display name and avatar.": "更新显示名称和头像。",
  "Open your activity, task, and usage ledger.": "打开你的活动、任务和用量记录。",
  "Toggle the app appearance.": "切换应用外观。",
  "Appearance": "外观",
  "End this browser session.": "结束当前浏览器会话。",
  "Switch to light mode": "切换到浅色模式",
  "Switch to dark mode": "切换到深色模式",
  "Local workspace board": "本地工作区看板",
  "Account": "账户",
  "Board": "看板",
  "Loading...": "正在加载...",
  "Loading": "正在加载",
  "Saving...": "正在保存...",
  "Saving…": "正在保存...",
  "Save": "保存",
  "Cancel": "取消",
  "Delete": "删除",
  "Archive": "归档",
  "Unarchive": "取消归档",
  "Refresh": "刷新",
  "Retry": "重试",
  "Close": "关闭",
  "Copied!": "已复制",
  "Copy": "复制",
  "Open": "打开",
  "Continue": "继续",
  "Back": "返回",
  "Next": "下一步",
  "Done": "完成",
  "Configure": "配置",
  "Command": "命令",
  "Command Palette": "命令面板",
  "Examples": "示例",
  "Example": "示例",
  "Not installed": "未安装",
  "Installed Plugins": "已安装插件",
  "Installed 插件": "已安装插件",
  "Install Example": "安装示例",
  "Hello World Widget (Example)": "Hello World Widget（示例）",
  "File Browser (Example)": "File Browser（示例）",
  "Kitchen Sink (Example)": "Kitchen Sink（示例）",
  "Orchestration Smoke (Example)": "Orchestration Smoke（示例）",
  "Reference UI plugin that adds a simple Hello World widget to the Paperclip dashboard.": "参考 UI 插件：在 Paperclip 仪表盘中添加一个简单的 Hello World 小组件。",
  "Example plugin that adds a Files link in project navigation plus a project detail file browser.": "示例插件：在项目导航中添加文件入口，并在项目详情中提供文件浏览器。",
  "Reference plugin that demonstrates the current Paperclip plugin API surface, bridge flows, UI extension surfaces, jobs, webhooks, tools, streams, and trusted local workspace/process demos.": "参考插件：演示当前 Paperclip 插件 API、bridge 流程、UI 扩展面、任务、webhook、工具、流式能力，以及受信任本地工作区/进程示例。",
  "Acceptance fixture for scoped plugin routes, restricted database namespaces, issue orchestration, documents, wakeups, summaries, and UI status surfaces.": "验收 fixture：覆盖受限插件路由、受限数据库命名空间、事项编排、文档、唤醒、摘要和 UI 状态面。",
  "The plugin runtime and API surface are still changing. Expect breaking changes while this feature settles.": "插件运行时和 API 面仍在变化。该能力稳定前可能出现破坏性变更。",
  "ready": "就绪",
  "blocked": "已阻断",
  "needs attention": "需要处理",
  "trusted": "受信任",
  "Ready": "就绪",
  "active": "活跃",
  "pending": "待处理",
  "paused": "已暂停",
  "error": "错误",
  "None": "无",
  "Default": "默认",
  "All": "全部",
  "Mine": "我的",
  "Recent": "最近",
  "RECENT": "最近",
  "recent": "最近",
  "Unread": "未读",
  "Pending": "待处理",
  "Active": "活跃",
  "Paused": "已暂停",
  "Error": "错误",
  "Resume": "继续",
  "Pause": "暂停",
  "Stop": "停止",
  "Edit": "编辑",
  "Upload": "上传",
  "Download": "下载",
  "Remove item": "移除项目",
  "Remove": "移除",
  "created": "已创建",
  "created company": "已创建公司",
  "issue read marked": "事项已标记为已读",
  "company": "公司",
  "company memberships": "公司成员身份",
  "plugin": "插件",
  "installed": "已安装",
  "upgraded": "已升级",
  "enabled": "已启用",
  "uninstalled": "已卸载",
  "Choose a role": "选择角色",
  "Select an agent": "选择代理",
  "Select a file to inspect.": "选择一个文件进行检查。",
  "Search users": "搜索用户",
  "No results found.": "未找到结果。",
  "No companies": "暂无公司",
  "No goals.": "暂无目标。",
  "No goals yet.": "暂无目标。",
  "No approvals yet.": "暂无审批。",
  "No projects yet.": "暂无项目。",
  "No new inbox items.": "暂无新的收件箱项目。",
  "No routines yet.": "暂无例程。",
  "No revisions yet": "暂无修订记录",
  "No labels": "无标签",
  "No project": "无项目",
  "No parent": "无父项",
  "No assignee": "未分配负责人",
  "Unassigned": "未分配",
  "Unlimited budget": "无限预算",
  "Uploading logo...": "正在上传标志...",
  "Saved": "已保存",
  "Rejected": "已拒绝",
  "Approved": "已批准",
  "Confirmed": "已确认",
  "Declined": "已拒绝",
  "Passed": "已通过",
  "Fixed": "固定",
  "Alpha": "测试阶段",
  "Budget": "预算",
  "Usage": "用量",
  "Debits": "借记",
  "Credits": "贷记",
  "Net": "净额",
  "Estimated": "预估",
  "Critical": "严重",
  "High": "高",
  "Low": "低",
  "True": "是",
  "False": "否",
  "Old": "旧版本",
  "New": "新版本",
  "Content": "内容",
  "Plain": "明文",
  "Secret": "密钥",
  "Source": "来源",
  "Key": "键",
  "Mode": "模式",
  "Label": "标签",
  "Type": "类型",
  "Name": "名称",
  "Email": "邮箱",
  "Password": "密码",
  "Role": "角色",
  "Status": "状态",
  "Priority": "优先级",
  "Assignee": "负责人",
  "Creator": "创建者",
  "Reviewer": "复核人",
  "Reviewers": "复核人",
  "Approver": "审批人",
  "Approvers": "审批人",
  "Owner": "所有者",
  "Admin": "管理员",
  "Description": "描述",
  "Summary": "摘要",
  "Title": "标题",
  "Risks": "风险",
  "Skills": "技能",
  "Capabilities": "能力",
  "Properties": "属性",
  "Documents": "文档",
  "Attachments": "附件",
  "Runs": "运行",
  "Workspace": "工作区",
  "Workspace card": "工作区卡片",
  "Workspace commands": "工作区命令",
  "Workspace facts": "工作区事实",
  "Services and jobs": "服务与任务",
  "Workspace settings": "工作区设置",
  "Source control": "源码控制",
  "Paths": "路径",
  "Branch": "分支",
  "Path": "路径",
  "Service": "服务",
  "Current state": "当前状态",
  "Advanced runtime JSON": "高级运行时 JSON",
  "General": "通用",
  "Experimental": "实验性",
  "Monthly": "每月",
  "MONTHLY": "每月",
  "Scheduler Heartbeats": "调度心跳",
  "Auth readiness": "认证就绪状态",
  "Bootstrap status": "引导状态",
  "Bootstrap invite": "引导邀请",
  "AUTH READINESS": "认证就绪状态",
  "BOOTSTRAP STATUS": "引导状态",
  "BOOTSTRAP INVITE": "引导邀请",
  "Enable Environments": "启用环境",
  "Enable Isolated Workspaces": "启用隔离工作区",
  "Auto-Restart Dev Server When Idle": "空闲时自动重启开发服务器",
  "Auto-Create Issue Recovery Tasks": "自动创建事项恢复任务",
  "Deployment and auth": "部署与认证",
  "Backup retention": "备份保留",
  "Daily": "每日",
  "Weekly": "每周",
  "Instance Access": "实例访问权限",
  "Company Access": "公司访问权限",
  "Company Invites": "公司邀请",
  "Join Request Queue": "加入请求队列",
  "Company Environments": "公司环境",
  "Environment support by adapter": "按适配器查看环境支持",
  "Local": "本地",
  "SSH": "SSH",
  "Sandbox": "沙箱",
  "Install Adapter": "安装适配器",
  "External adapters": "外部适配器",
  "External Adapters": "外部适配器",
  "External adapters are alpha.": "外部适配器仍处于 alpha 阶段。",
  "No external adapters installed": "尚未安装外部适配器",
  "Install an adapter package to extend model support.": "安装适配器包以扩展模型支持。",
  "Plugin Manager": "插件管理器",
  "Install Plugin": "安装插件",
  "Available Plugins": "可用插件",
  "Loading plugins...": "正在加载插件...",
  "Failed to load plugins.": "加载插件失败。",
  "About": "关于",
  "Author": "作者",
  "Categories": "分类",
  "Configure this plugin from Company Environments.": "请从公司环境中配置此插件。",
  "Loading plugin details...": "正在加载插件详情...",
  "Reinstall Adapter": "重新安装适配器",
  "Package": "包",
  "PACKAGES": "包",
  "packages": "包",
  "APPEARANCE": "外观",
  "HIRING": "招聘",
  "GRANTS": "授权",
  "ACTION": "操作",
  "Current": "当前",
  "Latest on npm": "npm 最新版本",
  "Install External Adapter": "安装外部适配器",
  "Loading adapters...": "正在加载适配器...",
  "Activity": "活动",
  "All Time": "全部时间",
  "All types": "全部类型",
  "Last 7 days": "最近 7 天",
  "Last 30 days": "最近 30 天",
  "By agent": "按代理",
  "By project": "按项目",
  "Overview": "概览",
  "Finance": "财务",
  "Inference ledger": "推理账本",
  "Inference spend": "推理花费",
  "Finance net": "财务净额",
  "Finance events": "财务事件",
  "Month to Date": "本月至今",
  "Year to Date": "本年至今",
  "Custom": "自定义",
  "INFERENCE SPEND": "推理花费",
  "BUDGET": "预算",
  "USAGE": "用量",
  "DEBITS": "借记",
  "CREDITS": "贷记",
  "NET": "净额",
  "ESTIMATED": "预估",
  "FINANCE NET": "财务净额",
  "FINANCE EVENTS": "财务事件",
  "No monthly cap configured": "未配置月度上限",
  "No cost events yet.": "暂无成本事件。",
  "No cost events in this period.": "此期间暂无成本事件。",
  "No finance events yet. Add account-level charges once biller invoices or credits land.": "暂无财务事件。计费方发票或抵扣到账后，可添加账户级费用。",
  "$0.00 debits · $0.00 credits": "$0.00 借记 · $0.00 贷记",
  "$0.00 estimated in range": "$0.00 范围内预估",
  "Request-scoped inference spend for the selected period.": "所选期间内按请求统计的推理花费。",
  "Refunds, offsets, and credit returns": "退款、抵扣和额度返还",
  "Debit minus credit for the selected period": "所选期间内借记减去贷记",
  "Inference spend, platform fees, credits, and live quota windows.": "推理花费、平台费用、抵扣和实时配额窗口。",
  "Recent financial events": "最近财务事件",
  "Financial event mix": "财务事件组合",
  "Finance ledger": "财务账本",
  "Provider": "提供方",
  "Providers": "提供方",
  "Billers": "计费方",
  "Budgets": "预算",
  "All providers": "全部提供方",
  "All billers": "全部计费方",
  "No finance events in this period.": "此期间暂无财务事件。",
  "Top-ups, fees, credits, commitments, and other non-request charges.": "充值、费用、抵扣、承诺用量及其他非请求费用。",
  "Account-level charges grouped by event kind.": "按事件类型分组的账户级费用。",
  "Run ledger": "运行账本",
  "Run": "运行",
  "Run now": "立即运行",
  "open": "打开",
  "runs": "运行",
  "Preview": "预览",
  "You have no agents.": "你还没有代理。",
  "New one here": "在这里新建一个",
  "No recent agent runs.": "暂无最近的代理运行。",
  "Agents Enabled": "已启用代理",
  "Agent Enabled": "已启用代理",
  "Tasks In Progress": "进行中的任务",
  "Month Spend": "本月花费",
  "Pending Approvals": "待处理审批",
  "Issues by Priority": "按优先级查看事项",
  "Issues by Status": "按状态查看事项",
  "Success Rate": "成功率",
  "No runs yet": "暂无运行",
  "Live runs": "实时运行",
  "Live Runs": "实时运行",
  "Live agent runs": "实时代理运行",
  "ACTIVE / RECENT": "活跃 / 最近",
  "Run Activity": "运行活动",
  "Showing up to 50": "最多显示 50 条",
  "No active or recent agent runs.": "暂无活跃或最近的代理运行。",
  "Child work": "子工作",
  "Elapsed": "已用时间",
  "Last useful action": "上次有效动作",
  "Next action:": "下一步动作：",
  "Runtime logs": "运行日志",
  "Run routine": "运行例程",
  "Routine": "例程",
  "routine": "例程",
  "routines": "例程",
  "New routine": "新建例程",
  "Recurring work definitions that materialize into auditable execution issues.": "会转化为可审计执行事项的周期性工作定义。",
  "Variables": "变量",
  "Default value": "默认值",
  "No default": "无默认值",
  "Options": "选项",
  "Schedule": "计划",
  "Signing mode": "签名模式",
  "Replay window (seconds)": "重放窗口（秒）",
  "Advanced delivery settings": "高级投递设置",
  "Sort": "排序",
  "Group": "分组",
  "For": "对象",
  "Project": "项目",
  "Sub-issue": "子事项",
  "Sub-issues": "子事项",
  "Sub-issue of": "父事项",
  "Blocked by": "阻断来源",
  "Blocking": "正在阻断",
  "Related work": "相关工作",
  "Jump to latest": "跳到最新",
  "Chat": "聊天",
  "Reply": "回复",
  "Send": "发送",
  "New document": "新建文档",
  "Revision history": "修订历史",
  "Loading revisions...": "正在加载修订记录...",
  "Select two revisions to compare.": "请选择两个修订版本进行比较。",
  "Both sides are the same revision.": "两侧是同一个修订版本。",
  "Upload attachment": "上传附件",
  "Filters": "筛选",
  "Quick filters": "快速筛选",
  "All categories": "全部分类",
  "OTHER RESULTS": "其他结果",
  "Other results": "其他结果",
  "My recent issues": "我最近的事项",
  "Join requests": "加入请求",
  "Failed runs": "失败运行",
  "Alerts": "告警",
  "All approval statuses": "全部审批状态",
  "Pending approval": "待审批",
  "Request type": "请求类型",
  "Join Requests": "加入请求",
  "Human": "人工",
  "Agent": "代理",
  "Pending human joins": "待处理人工加入",
  "Awaiting board review": "等待看板复核",
  "Humans": "人员",
  "User account": "用户账户",
  "Current memberships": "当前成员关系",
  "Invite history": "邀请历史",
  "Latest invite link": "最新邀请链接",
  "Invite history below keeps the audit trail.": "下方邀请历史会保留审计轨迹。",
  "Create new company": "创建新公司",
  "Rename on conflict": "冲突时重命名",
  "Skip on conflict": "冲突时跳过",
  "Replace existing": "替换已有内容",
  "Package files": "包文件",
  "Import source": "导入来源",
  "Display name": "显示名称",
  "Loading profile...": "正在加载个人资料...",
  "Tokens": "Token",
  "Spend": "花费",
  "Created": "创建时间",
  "Updated": "更新时间",
  "You": "你",
  "Last 14 days": "最近 14 天",
  "Recent tasks": "最近任务",
  "TASKS": "任务",
  "Tasks": "任务",
  "tasks": "任务",
  "No touched tasks yet.": "尚无接触过的任务。",
  "New Agent": "新建代理",
  "Add a new agent": "添加新代理",
  "Create your first agent": "创建你的第一个代理",
  "Advanced agent configuration": "高级代理配置",
  "Agent instructions file": "代理指令文件",
  "Reports to: N/A (CEO)": "汇报对象：无（CEO）",
  "Model": "模型",
  "MODEL": "模型",
  "model": "模型",
  "models": "模型",
  "Cheap model": "低成本模型",
  "CHEAP MODEL": "低成本模型",
  "Thinking effort": "思考强度",
  "Auto": "自动",
  "Enable Chrome": "启用 Chrome",
  "Skip permissions": "跳过权限检查",
  "Max turns per run": "每次运行最大轮次",
  "Choose": "选择",
  "Extra args (comma-separated)": "额外参数（逗号分隔）",
  "Environment variables": "环境变量",
  "Seal": "封存",
  "Run Policy": "运行策略",
  "Heartbeat on interval": "定时心跳",
  "No optional company skills installed yet.": "尚未安装可选公司技能。",
  "This will be the CEO": "这将成为 CEO",
  "Test Agent": "测试代理",
  "Create agent": "新建代理",
  "New agent": "新建代理",
  "Company skills": "公司技能",
  "Detail": "详情",
  "Add": "添加",
  "Paperclip managed": "Paperclip 托管",
  "Bundled Paperclip skills are read-only.": "内置 Paperclip 技能为只读。",
  "Paperclip bundled": "Paperclip 内置",
  "Read only": "只读",
  "USED BY": "使用者",
  "No agents attached": "没有关联代理",
  "View": "查看",
  "Code": "代码",
  "When to use": "何时使用",
  "Identity": "身份",
  "Execution": "执行",
  "Company default (Local)": "公司默认（本地）",
  "Adapter": "适配器",
  "No icons match": "没有匹配的图标",
  "Unsaved changes": "有未保存更改",
  "Specify path manually": "手动指定路径",
  "Find the folder in Finder.": "在 Finder 中找到文件夹。",
  "Paste the result into the path input.": "将结果粘贴到路径输入框。",
  "Windows (File Explorer)": "Windows（文件资源管理器）",
  "How to get a full path": "如何获取完整路径",
  "Open issue": "打开事项",
  "Open board": "打开看板",
  "Go home": "返回首页",
  "Sign in required": "需要登录",
  "Sign in / Create account": "登录 / 创建账户",
  "Approve Paperclip CLI access": "批准 Paperclip CLI 访问",
  "Invalid CLI auth URL.": "CLI 认证 URL 无效。",
  "Loading CLI auth challenge...": "正在加载 CLI 认证挑战...",
  "CLI auth challenge unavailable": "CLI 认证挑战不可用",
  "CLI auth challenge unavailable.": "CLI 认证挑战不可用。",
  "CLI access approved": "CLI 访问已批准",
  "Invalid board claim URL.": "看板认领 URL 无效。",
  "Loading claim challenge...": "正在加载认领挑战...",
  "Claim challenge unavailable": "认领挑战不可用",
  "Claim challenge unavailable.": "认领挑战不可用。",
  "Board ownership claimed": "看板所有权已认领",
  "Invalid invite token.": "邀请 token 无效。",
  "Loading invite...": "正在加载邀请...",
  "Checking your access...": "正在检查你的访问权限...",
  "Invite not available": "邀请不可用",
  "Opening company...": "正在打开公司...",
  "Approval page": "审批页面",
  "Claim secret": "认领密钥",
  "Message from inviter": "邀请人留言",
  "Submit agent details": "提交代理详情",
  "Agent name": "代理名称",
  "Adapter type": "适配器类型",
  "Issue chat review surface": "事项聊天评审界面",
  "Work": "工作",
  "Projects": "项目",
  "Hiring": "招聘",
  "Grants": "授权",
  "Action": "操作",
  "Company Packages": "公司包",
  "Issue documents": "事项文档",
  "Baseline metrics": "基线指标",
  "Fixture shape": "Fixture 形态",
  "Backlog": "待办",
  "Medium": "中",
  "Working": "工作中",
  "Built-in": "内置",
  "What to evaluate on this page": "此页面需要评估的内容",
  "Run Transcript Fixtures": "运行转录 Fixture",
  "User": "用户",
  "Input": "输入",
  "Result": "结果",
  "More": "更多",
  "Company rail": "公司栏",
  "Main company nav": "公司主导航",
  "Instance sidebar": "实例侧边栏",
  "Company settings sidebar": "公司设置侧边栏",
  "Breadcrumbs": "面包屑",
  "Account menu": "账户菜单",
  "Design Guide": "设计指南",
  "App components": "应用组件",
  "UI primitives": "UI 基础组件",
  "Core": "核心",
  "Component coverage": "组件覆盖",
  "COMPONENT COVERAGE": "组件覆盖",
  "Accent": "强调色",
  "Background": "背景",
  "Border": "边框",
  "Card": "卡片",
  "Destructive": "危险色",
  "Foreground": "前景",
  "Muted": "弱化色",
  "Muted foreground": "弱化前景",
  "Primary": "主色",
  "Primary foreground": "主色前景",
  "Ring": "焦点环",
  "Secondary": "次级色",
  "Sidebar": "侧边栏",
  "Sidebar border": "侧边栏边框",
  "Restart Required": "需要重启",
  "Auto-Restart On": "自动重启已开启",
  "Worktree": "工作树",
  "Changed": "已变更",
  "Pending migrations": "待执行迁移",
  "Dismiss notification": "关闭通知",
  "Mobile navigation": "移动端导航",
  "NOT FOUND": "未找到",
  "Not Found": "未找到",
  "Company not found": "公司未找到",
  "Page not found": "页面未找到",
  "Requested path:": "请求路径：",
  "Company name": "公司名称",
  "Logo": "标志",
  "Brand color": "品牌颜色",
  "Attachment size limit": "附件大小限制",
  "Require board approval for new hires": "新成员加入需要看板审批",
  "Generate OpenClaw Invite Prompt": "生成 OpenClaw 邀请提示词",
  "COMPANY PACKAGES": "公司包",
  "Export": "导出",
  "Import": "导入",
  "DANGER ZONE": "危险区域",
  "Danger Zone": "危险区域",
  "Archive company": "归档公司",
  "Ask them to visit Company Settings → Access to approve your request.": "请对方进入 公司设置 → 访问权限 审批你的请求。",
  "Press": "按下",
  "to close": "关闭",
  "then": "然后",
};

const PRIORITY_PHRASE_TRANSLATIONS: Array<[RegExp, string]> = [
  [/\bSkip to Main Content\b/g, "跳到主内容"],
  [/\bYou have no agents\.\s+New one here\b/gi, "你还没有代理。在这里新建一个"],
  [/\bone here\b/gi, "一个"],
  [/\bNo recent agent runs\.?/gi, "暂无最近的代理运行。"],
  [/\bNo active or recent agent runs\.?/gi, "暂无活跃或最近的代理运行。"],
  [/\bNo approvals yet\.?/gi, "暂无审批。"],
  [/\bNo goals yet\.?/gi, "暂无目标。"],
  [/\bNo new inbox items\.?/gi, "暂无新的收件箱项目。"],
  [/\bNo projects yet\.?/gi, "暂无项目。"],
  [/\bNo routines yet\. Use New routine to define the first recurring workflow\.?/gi, "暂无例程。请使用“新建例程”定义第一个周期性工作流。"],
  [/\bNo routines yet\. Use 新建 routine to define the first recurring workflow\.?/gi, "暂无例程。请使用“新建例程”定义第一个周期性工作流。"],
  [/\bNew routine\b/gi, "新建例程"],
  [/\b新建 routine\b/gi, "新建例程"],
  [/\broutine\b/gi, "例程"],
  [/\bRecurring work definitions that materialize into auditable execution issues\.?/gi, "会转化为可审计执行事项的周期性工作定义。"],
  [/\bActive runs first, followed by the most recent completed runs\.?/gi, "先显示活跃运行，然后显示最近完成的运行。"],
  [/\bACTIVE \/ RECENT\b/g, "活跃 / 最近"],
  [/^活跃 \/ RECENT$/g, "活跃 / 最近"],
  [/^活跃\s*\/\s*RECENT$/g, "活跃 / 最近"],
  [/\b(\d+) running, (\d+) paused, (\d+) errors\b/gi, "$1 运行中，$2 已暂停，$3 错误"],
  [/\b(\d+) running, (\d+) 已暂停, (\d+) errors\b/gi, "$1 运行中，$2 已暂停，$3 错误"],
  [/\b(\d+) open, (\d+) blocked\b/gi, "$1 打开，$2 已阻断"],
  [/\b(\d+) open, (\d+) 已阻断\b/gi, "$1 打开，$2 已阻断"],
  [/\bReview human and agent join requests outside the mixed inbox feed\. This queue uses the same approval mutations as the inline inbox cards\.?/gi, "在混合收件箱流之外复核人工和代理加入请求。此队列使用与内联收件箱卡片相同的审批变更。"],
  [/\bNo join requests match the current filters\.?/gi, "没有符合当前筛选条件的加入请求。"],
  [/\bSelect a company to review join requests\.?/gi, "选择公司以复核加入请求。"],
  [/\bLoading join requests…/g, "正在加载加入请求..."],
  [/\bYou do not have permission to review join requests for this company\.?/gi, "你没有复核该公司加入请求的权限。"],
  [/\bFailed to load join requests\.?/gi, "加载加入请求失败。"],
  [/\bReview human join requests before they become active company members\.?/gi, "在人工加入请求成为活跃公司成员前进行复核。"],
  [/\bManage company user memberships, membership status, and explicit permission grants for ([^.]+)\.?/gi, "管理 $1 的公司用户成员关系、成员状态和显式权限授权。"],
  [/\bManage human company memberships, status, and grants here\.?/gi, "在这里管理人工公司成员关系、状态和授权。"],
  [/\bNo explicit grants\b/gi, "没有显式授权"],
  [/\bSearch users, manage instance-admin status, and control which companies they can access\.?/gi, "搜索用户、管理实例管理员状态，并控制其可访问的公司。"],
  [/\bToggle company membership for this user\. New access defaults to an active operator membership\.?/gi, "切换该用户的公司成员身份。新增访问权限默认为活跃操作员成员。"],
  [/\bRemove instance admin\b/gi, "移除实例管理员"],
  [/\bGenerate a human invite link and choose the default access it should request\.?/gi, "生成人工邀请链接，并选择其默认请求的访问权限。"],
  [/\bCan assign tasks\.?/gi, "可分配任务。"],
  [/\bFull company access, including membership and permission management\.?/gi, "完整公司访问权限，包括成员和权限管理。"],
  [/\bEverything in Admin, plus managing members and permission grants\.?/gi, "包含管理员的全部权限，并可管理成员和权限授权。"],
  [/\bEverything in 管理员, plus managing members and permission grants\.?/gi, "包含管理员的全部权限，并可管理成员和权限授权。"],
  [/\bEach invite link is single-use\. The first successful use consumes the link and creates or reuses the matching join request before approval\.?/gi, "每个邀请链接只能使用一次。首次成功使用会消耗该链接，并在审批前创建或复用匹配的加入请求。"],
  [/\bReview invite status, role, inviter, and any linked join request\.?/gi, "复核邀请状态、角色、邀请人以及任何关联的加入请求。"],
  [/\bOpen join request queue\b/gi, "打开加入请求队列"],
  [/\bNo invites have been created for this company yet\.?/gi, "该公司尚未创建邀请。"],
  [/\bNew human invite links for company access\. New invite links are copied to your clipboard when they are generated\.?/gi, "新建用于公司访问权限的人工邀请链接。新邀请链接生成后会复制到剪贴板。"],
  [/\b新建 human invite links for 公司访问权限\. 新版本 invite links are copied to your clipboard when they are generated\.?/gi, "新建用于公司访问权限的人工邀请链接。新邀请链接生成后会复制到剪贴板。"],
  [/\bhuman invite links for 公司访问权限\. 新版本 invite links are copied to your clipboard when they are generated\.?/gi, "用于公司访问权限的人工邀请链接。新邀请链接生成后会复制到剪贴板。"],
  [/\bGenerate an OpenClaw agent invite snippet\.?/gi, "生成 OpenClaw 代理邀请片段。"],
  [/\bGenerate an OpenClaw 代理 invite snippet\.?/gi, "生成 OpenClaw 代理邀请片段。"],
  [/^导入 and export have moved to dedicated pages accessible from the$/gi, "导入和导出已移至专用页面，可从"],
  [/^组织 Chart$/gi, "组织图表"],
  [/^header\.$/gi, "头部进入。"],
  [/\bImport and export have moved to dedicated pages accessible from the Org Chart header\.?/gi, "导入和导出已移至专用页面，可从组织图表头部进入。"],
  [/\bImport and export have moved to dedicated pages accessible from the 组织 Chart header\.?/gi, "导入和导出已移至专用页面，可从组织图表头部进入。"],
  [/^导入 and export have moved to dedicated pages accessible from the 组织 Chart header\.?$/gi, "导入和导出已移至专用页面，可从组织图表头部进入。"],
  [/^导入 and export have moved to dedicated pages accessible from the Org Chart header\.?$/gi, "导入和导出已移至专用页面，可从组织图表头部进入。"],
  [/导入\s+and export have moved to dedicated pages accessible from the 组织 Chart header\.?/gi, "导入和导出已移至专用页面，可从组织图表头部进入。"],
  [/\band export have moved to dedicated pages accessible from the Org Chart header\.?/gi, "和导出已移至专用页面，可从组织图表头部进入。"],
  [/\band export have moved to dedicated pages accessible from the 组织 Chart header\.?/gi, "和导出已移至专用页面，可从组织图表头部进入。"],
  [/\bArchive this company to hide it from the sidebar\. This persists in the database\.?/gi, "归档该公司以从侧边栏隐藏。此操作会持久化到数据库。"],
  [/\b归档 this company to hide it from the sidebar\. This persists in the database\.?/gi, "归档该公司以从侧边栏隐藏。此操作会持久化到数据库。"],
  [/\bExternal adapters are alpha\.?/gi, "外部适配器仍处于 alpha 阶段。"],
  [/\bThe adapter plugin system is under active development\. APIs and storage format may change\. Use the power icon to hide adapters from agent menus without removing them\.?/gi, "适配器插件系统正在活跃开发中。API 和存储格式可能变化。可使用电源图标将适配器从代理菜单中隐藏，而无需移除它们。"],
  [/\bThe adapter plugin system is under 活跃 development\. APIs and storage format may change\. Use the power icon to hide adapters from 代理 menus without removing them\.?/gi, "适配器插件系统正在活跃开发中。API 和存储格式可能变化。可使用电源图标将适配器从代理菜单中隐藏，而无需移除它们。"],
  [/\bInstall an adapter package to extend model support\.?/gi, "安装适配器包以扩展模型支持。"],
  [/\bNo external adapters installed\b/gi, "尚未安装外部适配器"],
  [/\bCompany Environments are enabled\b/gi, "公司环境已启用"],
  [/\b公司环境 are enabled\b/gi, "公司环境已启用"],
  [/\bEnable Environments in instance experimental settings to manage company execution targets\.?/gi, "请在实例实验性设置中启用环境，以管理公司执行目标。"],
  [/\b启用环境 in instance experimental settings to manage company execution targets\.?/gi, "请在实例实验性设置中启用环境，以管理公司执行目标。"],
  [/\bInference spend, platform fees, credits, and live quota windows\.?/gi, "推理花费、平台费用、抵扣和实时配额窗口。"],
  [/\bLast (\d+) days\b/gi, "最近 $1 天"],
  [/\bLast (\d+) 天\b/gi, "最近 $1 天"],
  [/\bINFERENCE SPEND\b/g, "推理花费"],
  [/\bInference spend\b/gi, "推理花费"],
  [/\bFINANCE NET\b/g, "财务净额"],
  [/\bFinance Net\b/g, "财务净额"],
  [/\bFINANCE EVENTS\b/g, "财务事件"],
  [/\bFinance Events\b/g, "财务事件"],
  [/\b财务 NET\b/g, "财务净额"],
  [/\b财务 EVENTS\b/g, "财务事件"],
  [/\bBUDGET\b/g, "预算"],
  [/\bUSAGE\b/g, "用量"],
  [/\bDEBITS\b/g, "借记"],
  [/\bCREDITS\b/g, "贷记"],
  [/\bNET\b/g, "净额"],
  [/\bESTIMATED\b/g, "预估"],
  [/\b(\d+) tokens across request-scoped events\b/gi, "$1 个 token，来自请求级事件"],
  [/\b(\d+) total events in range\b/gi, "范围内共 $1 个事件"],
  [/\bEstimated debits that are not yet invoice-authoritative\b/gi, "尚未以发票为准的预估借记"],
  [/\$(\d+(?:\.\d+)?) debits · \$(\d+(?:\.\d+)?) credits/gi, "$$$1 借记 · $$$2 贷记"],
  [/\$(\d+(?:\.\d+)?) estimated in range/gi, "$$$1 范围内预估"],
  [/\b(\d+) available\b/gi, "$1 个可用"],
  [/\bUsed by\b/gi, "使用者"],
  [/\bRequest-scoped inference spend for the selected period\.?/gi, "所选期间内按请求统计的推理花费。"],
  [/\bRefunds, offsets, and credit returns\b/gi, "退款、抵扣和额度返还"],
  [/\bDebit minus credit for the selected period\b/gi, "所选期间内借记减去贷记"],
  [/\bWhat each agent consumed in the selected period\.?/gi, "所选期间内每个代理消耗的用量。"],
  [/\bWhat each 代理 consumed in the selected period\.?/gi, "所选期间内每个代理消耗的用量。"],
  [/\bNo cost events yet\.?/gi, "暂无成本事件。"],
  [/\bNo finance events yet\. Add account-level charges once biller invoices or credits land\.?/gi, "暂无财务事件。计费方发票或抵扣到账后，可添加账户级费用。"],
  [/\bRun costs attributed through project-linked issues\.?/gi, "通过项目关联事项归属的运行成本。"],
  [/\b运行 costs attributed through project-linked issues\.?/gi, "通过项目关联事项归属的运行成本。"],
  [/^plugin installed$/gi, "插件已安装"],
  [/^plugin upgraded$/gi, "插件已升级"],
  [/^plugin enabled$/gi, "插件已启用"],
  [/^plugin uninstalled$/gi, "插件已卸载"],
  [/^created company (.+)$/gi, "已创建公司 $1"],
  [/^created (DAR-\d+)[—-]\s*Dark Factory host UI verification issue$/gi, "已创建 $1 — Dark Factory 主机 UI 验证事项"],
  [/^issue read marked (DAR-\d+)[—-]\s*Dark Factory host UI verification issue$/gi, "已将事项标记为已读 $1 — Dark Factory 主机 UI 验证事项"],
  [/\bDark Factory host UI verification issue\b/gi, "Dark Factory 主机 UI 验证事项"],
  [/\bCreate your first agent to get started\.?/gi, "创建你的第一个代理即可开始。"],
  [/\bNo organizational hierarchy defined\.?/gi, "尚未定义组织层级。"],
  [/\bNo scheduler heartbeats match the current criteria\.?/gi, "没有符合当前条件的调度心跳。"],
  [/\bControl how your account appears in the sidebar and other board surfaces\.?/gi, "控制你的账户在侧边栏和其他看板界面的显示方式。"],
  [/\bClick the avatar to upload a new image\. Stored in Paperclip file storage for ([^.]+)\.?/gi, "点击头像上传新图片。文件会存储在 $1 的 Paperclip 文件存储中。"],
  [/\bClick the avatar to upload a new image\. Stored in Paperclip file storage for (.+)$/gi, "点击头像上传新图片。文件会存储在 $1 的 Paperclip 文件存储中。"],
  [/^Click the avatar to upload a new image\.$/gi, "点击头像上传新图片。"],
  [/\bClick the avatar to upload a new image\./gi, "点击头像上传新图片。"],
  [/\bShown in the sidebar account footer and comment author surfaces\.?/gi, "显示在侧边栏账户页脚和评论作者区域。"],
  [/\bEmail is managed by your auth session and is read-only here\.?/gi, "邮箱由认证会话管理，此处只读。"],
  [/\bUpload photo\b/gi, "上传照片"],
  [/\bSave profile\b/gi, "保存个人资料"],
  [/^Stored in Paperclip file storage for (.+)\.$/gi, "文件会存储在 $1 的 Paperclip 文件存储中。"],
  [/\bConfigure instance-wide preferences including log display, keyboard shortcuts, backup retention, and data sharing\.?/gi, "配置实例级偏好，包括日志显示、键盘快捷键、备份保留和数据共享。"],
  [/\bConfigure how long automatic database backups are retained\. Backups run roughly every hour and are compressed with gzip\. Within the daily window all backups are kept; beyond that, one backup per week and one per month are preserved\.?/gi, "配置自动数据库备份的保留时长。备份大约每小时运行一次，并使用 gzip 压缩。在每日窗口内会保留全部备份；超过该窗口后，每周和每月各保留一份。"],
  [/\bHide the username segment in home-directory paths and similar operator-visible log output\. Standalone username mentions outside of paths are not yet masked in the live transcript view\. This is off by default\.?/gi, "隐藏主目录路径和类似操作员可见日志输出中的用户名片段。实时转录视图中路径之外的独立用户名暂未遮蔽。默认关闭。"],
  [/\bLocal trusted mode is optimized for a local operator\. Browser requests run as local board context and no sign-in is required\.?/gi, "本地受信任模式针对本地操作员优化。浏览器请求会以本地看板上下文运行，且无需登录。"],
  [/\bEnable app keyboard shortcuts, including inbox navigation and global shortcuts like creating issues or toggling panels\. This is off by default\.?/gi, "启用应用键盘快捷键，包括收件箱导航，以及创建事项或切换面板等全局快捷键。默认关闭。"],
  [/\bControl whether thumbs up and thumbs down votes can send the voted AI output to Paperclip Labs\. Votes are always saved locally\.?/gi, "控制点赞和点踩是否可以将被投票的 AI 输出发送给 Paperclip Labs。投票始终会保存在本地。"],
  [/\bNo default is saved yet\. The next thumbs up or thumbs down choice will ask once and then save the answer here\.?/gi, "尚未保存默认选择。下一次点赞或点踩时会询问一次，并将答案保存在这里。"],
  [/\bShare voted AI outputs automatically\.?/gi, "自动共享被投票的 AI 输出。"],
  [/\bKeep voted AI outputs local only\.?/gi, "仅在本地保留被投票的 AI 输出。"],
  [/\bSign out of this Paperclip instance\. You will be redirected to the login page\.?/gi, "退出当前 Paperclip 实例。你将被重定向到登录页。"],
  [/\bOpt into features that are still being evaluated before they become default behavior\.?/gi, "启用仍在评估中、尚未成为默认行为的功能。"],
  [/\bShow environment management in Company Settings and allow project and agent environment assignment controls\.?/gi, "在公司设置中显示环境管理，并允许项目和代理分配环境。"],
  [/\bShow execution workspace controls in project configuration and allow isolated workspace behavior for new and existing issue runs\.?/gi, "在项目配置中显示执行工作区控制，并允许新旧事项运行使用隔离工作区行为。"],
  [/\bIn `pnpm dev:once`, wait for all queued and running local agent runs to finish, then restart the server automatically when backend changes or migrations make the current boot stale\.?/gi, "在 `pnpm dev:once` 中，等待所有排队和运行中的本地代理运行完成；当后端变更或迁移使当前启动过期时，自动重启服务器。"],
  [/\bIn `pnpm dev:once`, wait for all queued and running local agent runs to finish, then restart the server automatically when backend changes or migrations make the current boot stale\.?/gi, "在 `pnpm dev:once` 中，等待所有排队和运行中的本地代理运行完成；当后端变更或迁移使当前启动过期时，自动重启服务器。"],
  [/\bLet the heartbeat scheduler create recovery issues for issue dependency chains found inside the configured lookback window\.?/gi, "允许心跳调度器为配置回看窗口内发现的事项依赖链创建恢复事项。"],
  [/\bLookback hours must be a whole number from 1 to 720\.?/gi, "回看小时数必须是 1 到 720 之间的整数。"],
  [/\bLookback hours\b/gi, "回看小时数"],
  [/\bSave hours\b/gi, "保存小时数"],
  [/\bRun now\b/gi, "立即运行"],
  [/\bCurrent window: last (\d+) hours\.?/gi, "当前窗口：最近 $1 小时。"],
  [/\bwindow: last (\d+) hours\.?/gi, "窗口：最近 $1 小时。"],
  [/\bwindow: last (\d+) 小时\.?/gi, "窗口：最近 $1 小时。"],
  [/^当前 window: last (\d+) hours\.?$/gi, "当前窗口：最近 $1 小时。"],
  [/^当前 window: last (\d+) 小时\.?$/gi, "当前窗口：最近 $1 小时。"],
  [/\b当前 window: last (\d+) 小时\.?/gi, "当前窗口：最近 $1 小时。"],
  [/^当前 window: last$/gi, "当前窗口：最近"],
  [/^hours$/gi, "小时"],
  [/\bAgents? with a timer heartbeat enabled across all of your companies\.?/gi, "所有公司中已启用定时心跳的代理。"],
  [/\bNo pending approvals\.?/gi, "暂无待审批。"],
  [/\bNo company matches prefix "([^"]+)"\.?/gi, "没有公司匹配前缀“$1”。"],
  [/\bRequested path: (\/[^\s]+)\b/gi, "请求路径：$1"],
  [/^This issue conversation is empty\. Start with a message below\.?$/gi, "此事项对话为空。请在下方发送第一条消息。"],
  [/^本地 browser harness issue for Dark Factory bridge detail tab verification\.?$/gi, "本地 browser-harness 事项，用于 Dark Factory bridge 详情标签页验证。"],
  [/^Add blocker$/gi, "添加阻断项"],
  [/^添加 blocker$/gi, "添加阻断项"],
  [/^Add sub-issue$/gi, "添加子事项"],
  [/^添加 sub-issue$/gi, "添加子事项"],
  [/^Created by$/gi, "创建者"],
  [/^创建时间 by$/gi, "创建者"],
  [/^May (\d{1,2}), (\d{4})$/g, "$2年5月$1日"],
  [/\bOpen dashboard\b/gi, "打开仪表盘"],
  [/\bEvery component, style, and pattern used across Paperclip\.?/gi, "Paperclip 中使用的每个组件、样式和模式。"],
  [/\bThis page should be updated when new UI primitives or app-level patterns ship\.?/gi, "发布新的 UI 基础组件或应用级模式时，应同步更新此页面。"],
  [/\bCosts tab content\.?/gi, "成本标签页内容。"],
  [/\bAccount-level charges that do not map to a single inference request\.?/gi, "无法映射到单个推理请求的账户级费用。"],
  [/\bActive runs first, followed by the most recent completed runs\.?/gi, "先显示活跃运行，然后显示最近完成的运行。"],
  [/\bAdd Goal\b/g, "添加目标"],
  [/\bAdd Project\b/g, "添加项目"],
];

const PHRASE_TRANSLATIONS: Array<[RegExp, string]> = [
  [/\bHome\b/g, "首页"],
  [/\bIssues\b/g, "事项"],
  [/\bCreate\b/g, "新建"],
  [/\bAgents\b/g, "代理"],
  [/\bInbox\b/g, "收件箱"],
  [/\bDashboard\b/g, "仪表盘"],
  [/\bRoutines\b/g, "例程"],
  [/\bGoals\b/g, "目标"],
  [/\bOrg\b/g, "组织"],
  [/\bCosts\b/g, "成本"],
  [/\bInvites\b/g, "邀请"],
  [/\bHeartbeats\b/g, "心跳"],
  [/\bInstance settings\b/gi, "实例设置"],
  [/\bCompany settings\b/gi, "公司设置"],
  [/\bSettings\b/g, "设置"],
  [/\bSkip to Main Content\b/g, "跳到主内容"],
  [/\bBoard\b/g, "看板"],
  [/\bSkills\b/g, "技能"],
  [/\bAll\b/g, "全部"],
  [/\bMine\b/g, "我的"],
  [/\bRecent\b/g, "最近"],
  [/\bUnread\b/g, "未读"],
  [/\bPending\b/g, "待处理"],
  [/\bActive\b/g, "活跃"],
  [/\bPaused\b/g, "已暂停"],
  [/\bError\b/g, "错误"],
  [/\bCritical\b/g, "严重"],
  [/\bHigh\b/g, "高"],
  [/\bLow\b/g, "低"],
  [/\bHuman\b/g, "人工"],
  [/\bViewer\b/g, "查看者"],
  [/\bOperator\b/g, "操作员"],
  [/\bAdmin\b/g, "管理员"],
  [/\bKeyboard shortcuts\b/gi, "键盘快捷键"],
  [/\bOpen account menu\b/gi, "打开账户菜单"],
  [/\bNew issue\b/gi, "新建事项"],
  [/\bCreate your first agent to get started\.?/gi, "创建你的第一个代理即可开始。"],
  [/\bCreate your first company\b/gi, "创建第一个公司"],
  [/\bGet started by creating a company\.?/gi, "先创建一个公司即可开始。"],
  [/\bGet started by creating a company and your first agent\.?/gi, "先创建一个公司和第一个代理即可开始。"],
  [/\bRun onboarding again to create another company and seed its first agent\.?/gi, "再次运行引导流程，创建另一个公司并初始化第一个代理。"],
  [/\bRun onboarding again to add an agent and a starter task for this company\.?/gi, "再次运行引导流程，为该公司添加代理和起始任务。"],
  [/\bAdd Agent\b/g, "添加代理"],
  [/\bStart Onboarding\b/g, "开始引导"],
  [/\bNew Company\b/g, "新建公司"],
  [/\bSearch current page or quick search\b/gi, "搜索当前页面或快速搜索"],
  [/\bGo to inbox\b/gi, "转到收件箱"],
  [/\bFocus comment composer\b/gi, "聚焦评论输入框"],
  [/\bShow keyboard shortcuts\b/gi, "显示键盘快捷键"],
  [/\bToggle sidebar\b/gi, "切换侧边栏"],
  [/\bToggle panel\b/gi, "切换面板"],
  [/\bMark as read\b/gi, "标为已读"],
  [/\bMark as unread\b/gi, "标为未读"],
  [/\bQuick-archive back to inbox\b/gi, "快速归档并返回收件箱"],
  [/\bShortcuts are disabled in text fields\b/gi, "文本输入区域中快捷键已停用"],
  [/\bNo account yet\?/gi, "还没有账户？"],
  [/\bAlready signed up before\?/gi, "之前已经注册过？"],
  [/\bUse your email and password to access this instance\.?/gi, "使用邮箱和密码访问此实例。"],
  [/\bCreate an account for this instance\.?/gi, "为此实例创建账户。"],
  [/\bCompany access updated\b/gi, "公司访问权限已更新"],
  [/\bCompany access\b/gi, "公司访问权限"],
  [/\bSave company access\b/gi, "保存公司访问权限"],
  [/\bLoading user access…/g, "正在加载用户访问权限..."],
  [/\bFailed to load user access\.?/gi, "加载用户访问权限失败。"],
  [/\bSelect a user to inspect instance access\.?/gi, "选择用户以查看实例访问权限。"],
  [/\bInstance admin access is required to manage users\.?/gi, "需要实例管理员权限才能管理用户。"],
  [/\bSearch users, manage instance-admin status, and control which companies they can access\.?/gi, "搜索用户、管理实例管理员状态，并控制其可访问的公司。"],
  [/\bToggle company membership for this user\. New access defaults to an active operator membership\.?/gi, "切换该用户的公司成员身份。新增访问权限默认为活跃操作员成员。"],
  [/\bactive company memberships\b/gi, "个活跃公司成员身份"],
  [/\b(\d+) 活跃 company memberships\b/gi, "$1 个活跃公司成员身份"],
  [/\bThis URL includes the current Paperclip domain returned by the server\.?/gi, "该 URL 包含服务器返回的当前 Paperclip 域名。"],
  [/\bAsk them to visit Company Settings → Access to approve your request\.?/gi, "请对方进入 公司设置 → 访问权限 审批你的请求。"],
  [/\bYou've been invited to join Paperclip\b/gi, "你已受邀加入 Paperclip"],
  [/\bAccept company invite\b/gi, "接受公司邀请"],
  [/\bRequested access\b/gi, "请求的访问权限"],
  [/\bCan view company work and follow along without operational permissions\.?/gi, "可查看公司工作并跟进进展，但没有操作权限。"],
  [/\bRecommended for people who need to help run work without managing access\.?/gi, "适合协助执行工作但不管理访问权限的成员。"],
  [/\bRecommended for operators who need to invite people, create agents, and approve joins\.?/gi, "适合需要邀请成员、创建代理并审批加入请求的操作员。"],
  [/\bFull company access, including membership and permission management\.?/gi, "完整公司访问权限，包括成员和权限管理。"],
  [/\bCan create agents, invite users, assign tasks, and approve join requests\.?/gi, "可创建代理、邀请用户、分配任务并审批加入请求。"],
  [/\bSelect a company to view costs\.?/gi, "选择公司以查看成本。"],
  [/\bBy project\b/gi, "按项目"],
  [/\bNo project-attributed run costs yet\.?/gi, "暂无归属到项目的运行成本。"],
  [/\bUnattributed\b/gi, "未归属"],
  [/\bPending approvals\b/gi, "待审批"],
  [/\bPaused agents\b/gi, "已暂停代理"],
  [/\bPaused projects\b/gi, "已暂停项目"],
  [/\bProject execution blocked by budget\b/gi, "项目执行被预算阻断"],
  [/\bBudget override approvals awaiting board action\b/gi, "等待看板处理的预算覆盖审批"],
  [/\bCompany-wide monthly policy\.?/gi, "公司级月度策略。"],
  [/\bRecurring monthly spend policies for individual agents\.?/gi, "单个代理的月度周期支出策略。"],
  [/\bLifetime spend policies for execution-bound projects\.?/gi, "执行绑定项目的生命周期支出策略。"],
  [/\bNo budget policies yet\.?/gi, "尚无预算策略。"],
  [/\bNo organizational hierarchy defined\.?/gi, "尚未定义组织层级。"],
  [/\bNo scheduler heartbeats match the current criteria\.?/gi, "没有符合当前条件的调度心跳。"],
  [/\bControl how your account appears in the sidebar and other board surfaces\.?/gi, "控制你的账户在侧边栏和其他看板界面的显示方式。"],
  [/\bClick the avatar to upload a new image\. Stored in Paperclip file storage for ([^.]+)\.?/gi, "点击头像上传新图片。文件会存储在 $1 的 Paperclip 文件存储中。"],
  [/\bShown in the sidebar account footer and comment author surfaces\.?/gi, "显示在侧边栏账户页脚和评论作者区域。"],
  [/\bEmail is managed by your auth session and is read-only here\.?/gi, "邮箱由认证会话管理，此处只读。"],
  [/\bUpload photo\b/gi, "上传照片"],
  [/\bSave profile\b/gi, "保存个人资料"],
  [/\bConfigure instance-wide preferences including log display, keyboard shortcuts, backup retention, and data sharing\.?/gi, "配置实例级偏好，包括日志显示、键盘快捷键、备份保留和数据共享。"],
  [/\bLocal trusted mode is optimized for a local operator\. Browser requests run as local board context and no sign-in is required\.?/gi, "本地受信任模式针对本地操作员优化。浏览器请求会以本地看板上下文运行，且无需登录。"],
  [/\bLocal trusted\b/gi, "本地受信任"],
  [/\bAUTH READINESS\b/g, "认证就绪状态"],
  [/\bBOOTSTRAP STATUS\b/g, "引导状态"],
  [/\bBOOTSTRAP INVITE\b/g, "引导邀请"],
  [/\bCensor username in logs\b/gi, "在日志中隐藏用户名"],
  [/\bEnable app keyboard shortcuts, including inbox navigation and global shortcuts like creating issues or toggling panels\. This is off by default\.?/gi, "启用应用键盘快捷键，包括收件箱导航，以及创建事项或切换面板等全局快捷键。默认关闭。"],
  [/\bAI feedback sharing\b/gi, "AI 反馈共享"],
  [/\bControl whether thumbs up and thumbs down votes can send the voted AI output to Paperclip Labs\. Votes are always saved locally\.?/gi, "控制点赞和点踩是否可以将被投票的 AI 输出发送给 Paperclip Labs。投票始终会保存在本地。"],
  [/\bRead our terms of service\b/gi, "阅读服务条款"],
  [/\bNo default is saved yet\. The next thumbs up or thumbs down choice will ask once and then save the answer here\.?/gi, "尚未保存默认选择。下一次点赞或点踩时会询问一次，并将答案保存在这里。"],
  [/\bAlways allow\b/gi, "始终允许"],
  [/\bShare voted AI outputs automatically\.?/gi, "自动共享被投票的 AI 输出。"],
  [/\bDon't allow\b/gi, "不允许"],
  [/\bKeep voted AI outputs local only\.?/gi, "仅在本地保留被投票的 AI 输出。"],
  [/\bSign out of this Paperclip instance\. You will be redirected to the login page\.?/gi, "退出当前 Paperclip 实例。你将被重定向到登录页。"],
  [/\bOpt into features that are still being evaluated before they become default behavior\.?/gi, "启用仍在评估中、尚未成为默认行为的功能。"],
  [/\bShow environment management in Company Settings and allow project and agent environment assignment controls\.?/gi, "在公司设置中显示环境管理，并允许项目和代理分配环境。"],
  [/\bShow execution workspace controls in project configuration and allow isolated workspace behavior for new and existing issue runs\.?/gi, "在项目配置中显示执行工作区控制，并允许新旧事项运行使用隔离工作区行为。"],
  [/\bLet the heartbeat scheduler create recovery issues for issue dependency chains found inside the configured lookback window\.?/gi, "允许心跳调度器为配置回看窗口内发现的事项依赖链创建恢复事项。"],
  [/\bLookback hours\b/gi, "回看小时数"],
  [/\bSave hours\b/gi, "保存小时数"],
  [/\bRun now\b/gi, "立即运行"],
  [/\bCurrent window: last (\d+) hours\.?/gi, "当前窗口：最近 $1 小时。"],
  [/\bAgent with a timer heartbeat enabled across all of your companies\.?/gi, "所有公司中已启用定时心跳的代理。"],
  [/\bAgents with a timer heartbeat enabled across all of your companies\.?/gi, "所有公司中已启用定时心跳的代理。"],
  [/\bNo pending approvals\.?/gi, "暂无待审批。"],
  [/\bCompany not found\b/gi, "公司未找到"],
  [/\bNo company matches prefix "([^"]+)"\.?/gi, "没有公司匹配前缀“$1”。"],
  [/\bRequested path: (\/[^\s]+)\b/gi, "请求路径：$1"],
  [/\bOpen dashboard\b/gi, "打开仪表盘"],
  [/\bEvery component, style, and pattern used across Paperclip\.?/gi, "Paperclip 中使用的每个组件、样式和模式。"],
  [/\bThis page should be updated when new UI primitives or app-level patterns ship\.?/gi, "发布新的 UI 基础组件或应用级模式时，应同步更新此页面。"],
  [/\bCosts tab content\.?/gi, "成本标签页内容。"],
  [/\bAccount-level charges that do not map to a single inference request\.?/gi, "无法映射到单个推理请求的账户级费用。"],
  [/\bActive runs first, followed by the most recent completed runs\.?/gi, "先显示活跃运行，然后显示最近完成的运行。"],
  [/\bAdd Goal\b/g, "添加目标"],
  [/\bAdd Project\b/g, "添加项目"],
  [/\bAll providers\b/gi, "全部提供方"],
  [/\bpackages\b/g, "包"],
  [/\brecent\b/g, "最近"],
  [/\broutines\b/g, "例程"],
  [/\bruns\b/g, "运行"],
  [/\btasks\b/g, "任务"],
  [/\bmodels\b/g, "模型"],
  [/\bmodel\b/g, "模型"],
  [/\baccess\b/g, "访问权限"],
  [/^公司 access$/gi, "公司访问权限"],
  [/^公司 PACKAGES$/g, "公司包"],
  [/^最近 TASKS$/g, "最近任务"],
  [/^主色 MODEL$/g, "主色模型"],
  [/^Provider 状态$/g, "提供方状态"],
  [/^Provider 角色$/g, "提供方角色"],
  [/^主执行 Provider \(primary_execution\)$/g, "主执行提供方 (primary_execution)"],
  [/^是否联系 Provider$/g, "是否联系提供方"],
  [/Provider 阻断/g, "提供方阻断"],
  [/Provider 降级/g, "提供方降级"],
  [/Provider 恢复/g, "提供方恢复"],
  [/^回调 receipt$/g, "回调回执"],
  [/^receipt 状态$/g, "回执状态"],
  [/\breceipt\b/gi, "回执"],
  [/\bNo built-in grants\.?/gi, "没有内置授权。"],
  [/\bOptional skills from the company library\. Built-in Paperclip runtime skills are added automatically\.?/gi, "来自公司技能库的可选技能。内置 Paperclip 运行时技能会自动添加。"],
  [/^Optional skills from the company library\. 内置 Paperclip runtime skills are added automatically\.?$/gi, "来自公司技能库的可选技能。内置 Paperclip 运行时技能会自动添加。"],
  [/^Optional skills from the 公司 library\. 内置 Paperclip runtime skills are added automatically\.?$/gi, "来自公司技能库的可选技能。内置 Paperclip 运行时技能会自动添加。"],
  [/\bPermissions & Configuration\b/gi, "权限与配置"],
  [/\bUsed when a run requests the cheap profile \(e\.g\. routine summaries\)\. The primary model stays unchanged\.?/gi, "当运行请求低成本配置（例如例程摘要）时使用。主模型保持不变。"],
  [/^Used when a run requests the cheap profile \(e\.g\. 例程 summaries\)\. The primary 模型 stays unchanged\.?$/gi, "当运行请求低成本配置（例如例程摘要）时使用。主模型保持不变。"],
  [/\bPAPERCLIP_\* variables are injected automatically at runtime\.?/gi, "PAPERCLIP_* 变量会在运行时自动注入。"],
  [/\bNo optional company skills installed yet\.?/gi, "尚未安装可选公司技能。"],
  [/^Used when a run requests the cheap profile \(e\.g\. 例程 summaries\)\. The primary model stays unchanged\.?$/gi, "当运行请求低成本配置（例如例程摘要）时使用。主模型保持不变。"],
  [/\bThis will be the CEO\b/gi, "这将成为 CEO"],
  [/\bNew agent\b/gi, "新建代理"],
  [/\bagent\b/gi, "代理"],
  [/(\d+)\s+days\b/gi, "$1 天"],
  [/(\d+)\s+weeks\b/gi, "$1 周"],
  [/(\d+)\s+week\b/gi, "$1 周"],
  [/(\d+)\s+months\b/gi, "$1 月"],
  [/(\d+)\s+month\b/gi, "$1 月"],
  [/\bRemove instance admin\b/gi, "移除实例管理员"],
  [/\bYou cannot remove yourself\.?/gi, "不能移除你自己。"],
  [/^你 cannot remove yourself\.?$/gi, "不能移除你自己。"],
  [/^To retest the first-use prompt in local dev, remove the$/gi, "要在本地开发中重新测试首次使用提示，请移除"],
  [/^key from the$/gi, "这个键，位置在"],
  [/^JSON row for this instance, or set it back to$/gi, "此实例的 JSON 行；也可以把它改回"],
  [/^\. Unset and$/gi, "。未设置和"],
  [/^both mean no default has been chosen yet\.$/gi, "都表示尚未选择默认值。"],
  [/\bkey from the\b/gi, "这个键，位置在"],
  [/\bJSON row for this instance, or set it back to\b/gi, "此实例的 JSON 行；也可以把它改回"],
  [/\bUnset and\b/gi, "未设置和"],
  [/\bboth mean no default has been chosen yet\.?/gi, "都表示尚未选择默认值。"],
  [/\bBuilt-in adapter\b/gi, "内置适配器"],
  [/\bBuilt-in Adapters\b/gi, "内置适配器"],
  [/\btrusted\b/gi, "受信任"],
  [/\bRestart\b/g, "重启"],
  [/\bupdated\b/g, "更新于"],
  [/^just now$/gi, "刚刚"],
  [/^(\d+)h ago$/gi, "$1 小时前"],
  [/^(\d+)m ago$/gi, "$1 分钟前"],
  [/^(\d+)d ago$/gi, "$1 天前"],
  [/\blive run\b/g, "个实时运行"],
  [/\blive runs\b/g, "个实时运行"],
  [/\bWaiting for\b/g, "正在等待"],
  [/\bto finish\b/g, "完成"],
  [/\bAuto-restart will trigger when the instance is idle\b/gi, "实例空闲后将自动重启"],
  [/\bbackend files changed and migrations are pending\b/gi, "后端文件已变更，且存在待执行迁移"],
  [/\bpending migrations need a fresh boot\b/gi, "待执行迁移需要重新启动"],
  [/\bbackend files changed since this server booted\b/gi, "服务器启动后后端文件已变更"],
  [/^导入 and export have moved to dedicated pages accessible from the 组织 Chart header\.?$/gi, "导入和导出已移至专用页面，可从组织图表头部进入。"],
  [/导入\s+and export have moved to dedicated pages accessible from the 组织 Chart header\.?/gi, "导入和导出已移至专用页面，可从组织图表头部进入。"],
];

const VALUE_PATTERN = /^[\s\p{L}\p{N}.,:;!?'"`()/_?+\-—·$%&*#@→（）【】“”•]+$/u;
const EXACT_PHRASE_SKIP_SOURCES = new Set([
  "access",
  "company",
  "company access",
  "created",
  "enabled",
  "installed",
  "model",
  "models",
  "packages",
  "plugin",
  "recent",
  "routine",
  "routines",
  "runs",
  "tasks",
  "uninstalled",
  "upgraded",
]);
const EXACT_PHRASE_TRANSLATIONS = Object.entries(EXACT_TRANSLATIONS)
  .filter(([source]) => /[A-Za-z]/.test(source) && source.length > 2 && !EXACT_PHRASE_SKIP_SOURCES.has(source))
  .sort(([left], [right]) => right.length - left.length);

let observer: MutationObserver | null = null;
let scheduled = false;
const POST_INSTALL_RESCAN_DELAYS_MS = [0, 50, 250, 750, 1500] as const;

export function translateZhCnText(input: string): string {
  if (!input.trim()) return input;
  const exact = EXACT_TRANSLATIONS[input.trim()];
  if (exact) return input.replace(input.trim(), exact);

  let output = translatePriorityPhrases(input);
  output = translateExactPhrases(output);
  for (const [pattern, replacement] of PHRASE_TRANSLATIONS) {
    output = output.replace(pattern, replacement);
  }
  output = translatePriorityPhrases(output);
  return normalizeTranslatedWhitespace(output);
}

export function localizeDocumentZhCn(root: ParentNode = document): void {
  if (typeof document === "undefined") return;
  document.documentElement.lang = "zh-CN";
  if (document.title === "Paperclip" || /Paperclip/i.test(document.title)) {
    document.title = translateZhCnText(document.title);
  }
  localizeTextNodes(root);
  localizeElementText(root);
  localizeAttributes(root);
}

export function installZhCnLocalization(): void {
  if (typeof document === "undefined" || typeof MutationObserver === "undefined") return;
  localizeDocumentZhCn(document);
  scheduleZhCnRescans();
  if (observer) return;

  observer = new MutationObserver(() => {
    if (scheduled) return;
    scheduled = true;
    window.requestAnimationFrame(() => {
      scheduled = false;
      localizeDocumentZhCn(document);
      scheduleZhCnRescans();
    });
  });
  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: [...ZH_CN_ATTRIBUTE_NAMES],
    childList: true,
    characterData: true,
    subtree: true,
  });
  window.addEventListener("hashchange", scheduleZhCnRescans);
  window.addEventListener("popstate", scheduleZhCnRescans);
}

export function uninstallZhCnLocalizationForTests(): void {
  observer?.disconnect();
  observer = null;
  scheduled = false;
  if (typeof window !== "undefined") {
    window.removeEventListener("hashchange", scheduleZhCnRescans);
    window.removeEventListener("popstate", scheduleZhCnRescans);
  }
}

function scheduleZhCnRescans(): void {
  if (typeof window === "undefined") return;
  for (const delay of POST_INSTALL_RESCAN_DELAYS_MS) {
    window.setTimeout(() => localizeDocumentZhCn(document), delay);
  }
}

function localizeTextNodes(root: ParentNode): void {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const parent = node.parentElement;
      if (!parent) return NodeFilter.FILTER_REJECT;
      if (["SCRIPT", "STYLE", "CODE", "PRE", "KBD", "TEXTAREA"].includes(parent.tagName)) {
        return NodeFilter.FILTER_REJECT;
      }
      const value = node.nodeValue ?? "";
      if (!VALUE_PATTERN.test(value) || /[{}<>]/.test(value)) return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    },
  });
  const nodes: Text[] = [];
  while (walker.nextNode()) {
    nodes.push(walker.currentNode as Text);
  }
  for (const node of nodes) {
    const current = node.nodeValue ?? "";
    const translated = translateZhCnText(current);
    if (translated !== current) {
      node.nodeValue = translated;
    }
  }
}

function localizeAttributes(root: ParentNode): void {
  const elements = root instanceof Element
    ? [root, ...Array.from(root.querySelectorAll("*"))]
    : Array.from(root.querySelectorAll("*"));
  for (const element of elements) {
    for (const attribute of ZH_CN_ATTRIBUTE_NAMES) {
      const value = element.getAttribute(attribute);
      if (!value || !VALUE_PATTERN.test(value)) continue;
      const translated = translateZhCnText(value);
      if (translated !== value) {
        element.setAttribute(attribute, translated);
      }
    }
  }
}

function localizeElementText(root: ParentNode): void {
  const elements = root instanceof Element
    ? [root, ...Array.from(root.querySelectorAll("*"))]
    : Array.from(root.querySelectorAll("*"));
  for (const element of elements) {
    if (element.childElementCount > 0) continue;
    if (["SCRIPT", "STYLE", "CODE", "PRE", "KBD", "TEXTAREA"].includes(element.tagName)) continue;
    const value = element.textContent ?? "";
    if (!value || !VALUE_PATTERN.test(value) || /[{}<>]/.test(value)) continue;
    const translated = translateZhCnText(value);
    if (translated !== value) {
      element.textContent = translated;
    }
  }
}

function translateExactPhrases(input: string): string {
  let output = input;
  for (const [source, replacement] of EXACT_PHRASE_TRANSLATIONS) {
    if (!output.includes(source)) continue;
    const pattern = new RegExp(
      `(^|[^\\p{L}\\p{N}_-])${escapeRegExp(source)}(?=$|[^\\p{L}\\p{N}_-])`,
      "gu",
    );
    output = output.replace(pattern, `$1${replacement}`);
  }
  return output;
}

function translatePriorityPhrases(input: string): string {
  let output = input;
  for (const [pattern, replacement] of PRIORITY_PHRASE_TRANSLATIONS) {
    output = output.replace(pattern, replacement);
  }
  return output;
}

function escapeRegExp(input: string): string {
  return input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function normalizeTranslatedWhitespace(input: string): string {
  return input
    .replace(/当前\s+窗口/g, "当前窗口")
    .replace(/新建\s+一个/g, "新建一个")
    .replace(/(\d+) 打开,\s*(\d+) 已阻断/g, "$1 打开，$2 已阻断")
    .replace(/关联\s+运行 ID/g, "关联运行 ID")
    .replace(/导入\s+和导出/g, "导入和导出")
    .replace(/导入\s+and export have moved to dedicated pages accessible from the 组织 Chart header\.?/g, "导入和导出已移至专用页面，可从组织图表头部进入。")
    .replace(/导入\s+and export have moved to dedicated pages accessible from the Org Chart header\.?/g, "导入和导出已移至专用页面，可从组织图表头部进入。")
    .replace(/组织\s+Chart/g, "组织图表")
    .replace(/活跃\s*\/\s*RECENT/g, "活跃 / 最近")
    .replace(/\bINFERENCE SPEND\b/g, "推理花费")
    .replace(/\bBUDGET\b/g, "预算")
    .replace(/\bUSAGE\b/g, "用量")
    .replace(/\bDEBITS\b/g, "借记")
    .replace(/\bCREDITS\b/g, "贷记")
    .replace(/\bESTIMATED\b/g, "预估")
    .replace(/\bFINANCE NET\b/g, "财务净额")
    .replace(/\bFINANCE EVENTS\b/g, "财务事件")
    .replace(/财务\s+NET/g, "财务净额")
    .replace(/财务\s+EVENTS/g, "财务事件")
    .replace(/新建\s+routine/g, "新建例程")
    .replace(/Use 新建例程 to define the first recurring workflow\.?/g, "请使用“新建例程”定义第一个周期性工作流。")
    .replace(/Use 新建\s+例程 to define the first recurring workflow\.?/g, "请使用“新建例程”定义第一个周期性工作流。")
    .replace(/暂无例程。\s*Use 新建\s+例程 to define the first recurring workflow\.?/g, "暂无例程。请使用“新建例程”定义第一个周期性工作流。")
    .replace(/暂无例程。\s*请使用/g, "暂无例程。请使用")
    .replace(/提供方\s+状态/g, "提供方状态")
    .replace(/提供方\s+角色/g, "提供方角色")
    .replace(/主执行\s+提供方/g, "主执行提供方")
    .replace(/提供方\s+阻断/g, "提供方阻断")
    .replace(/公司\s+包/g, "公司包")
    .replace(/公司\s+Packages/g, "公司包")
    .replace(/公司\s+访问权限/g, "公司访问权限")
    .replace(/(\d+)\s+活跃\s+公司成员身份/g, "$1 个活跃公司成员身份")
    .replace(/启用环境 in instance experimental settings to manage company execution targets\.?/g, "请在实例实验性设置中启用环境，以管理公司执行目标。")
    .replace(/主色\s+MODEL/g, "主色模型")
    .replace(/主色\s+模型/g, "主色模型")
    .replace(/最近\s+TASKS/g, "最近任务")
    .replace(/最近\s+任务/g, "最近任务")
    .replace(/新建\s+用于/g, "新建用于")
    .replace(/(\d+)\s+例程s/g, "$1 个例程")
    .replace(/(\d+)\s+模型/g, "$1 个模型")
    .replace(/创建时间\s+(\d+)\s*小时前/g, "创建时间 $1 小时前");
}
